# NextEvent Go Configuration
# Migrated from .NET Core configuration

# Application Settings
app:
  name: "NextEvent"
  version: "2.0.0"
  environment: "development"
  self_url: "http://0.0.0.0:5008"
  is_development: true
  cors_origins:
    - "https://*.colorcon.com.cn"
    - "https://*.NextEvent.com"
    - "http://localhost:4200"
    - "http://localhost:3000"
    - "http://localhost:3100"
    - "http://127.0.0.1:29597"
    - "http://192.168.10.208:3000"

# Server Configuration
server:
  host: "0.0.0.0"
  port: 5008
  https_port: 5009
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  max_header_bytes: 1048576

# Database Configuration
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  name: "NextEventDB6"
  username: "root"
  password: "~Brook1226,"
  charset: "utf8mb4"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600s
  allow_user_variables: true
  allow_load_local_infile: true
  connection_string: "root:~Brook1226,@tcp(localhost:3306)/NextEventDB6?charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  password: "mypassword"
  database: 1
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 300s

# JWT Configuration
jwt:
  secret_key: "dzehzRz9a8asdfasfdadfasdfasdfafsdadfasbasdf="
  issuer: "ZenTeamNextEvent"
  audience: "ZenTeamNextEvent"
  expiration_hours: 24
  refresh_expiration_hours: 168 # 7 days
  algorithm: "HS256"

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"
  file_path: "logs/app.log"
  max_size: 100 # MB
  max_backups: 10
  max_age: 30 # days
  compress: true
  overrides:
    "github.com/gin-gonic/gin": "info"
    "gorm.io": "info"
    "github.com/go-redis/redis": "info"

# WeChat Configuration
wechat:
  public_account:
    app_id: "wx9be741fb80d04fb9"
    app_secret: "5e12e8a8f9b4e25e934b41c2a71b030b"
    token: "brook1226"
    encoding_aes_key: "2q4bzKQpWMywVriwWjPrnFGMlDzn5F2awp1QSCxSs3h"
    verify_signature: true
    cache_access_token: true
    access_token_cache_key: "wechat:access_token"
    access_token_expire_time: 7200s
  mini_app:
    app_id: "wxc320e6056994506c"
    app_secret: "75f7b7e786296426c8cefdb5d39f2387"
    cache_access_token: true
    access_token_cache_key: "wechat:miniapp:access_token"

# Message Queue Configuration (CAP equivalent)
message_queue:
  enabled: true
  provider: "rabbitmq" # rabbitmq, redis, nats
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    vhost: "/"
    exchange: "nextevent.events"
    queue_prefix: "nextevent"
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false

# ElasticSearch Configuration
elasticsearch:
  enabled: false
  url: "http://es.cn"
  username: "elastic"
  password: "aVVhjQ95RP7nbwNy"
  index_format: "companyname.projectname.development.{date}"
  search_index_format: "companyname.projectname.development*"
  timeout: 30s
  retry_on_status: [502, 503, 504]
  max_retries: 3

# HTTP Client Configuration
http_clients:
  sts:
    name: "Sts"
    base_url: "http://localhost:44354"
    timeout: 30s
    retry_count: 3
    retry_delay: 1s

# Service Discovery (Consul)
consul:
  enabled: false
  host: "http://localhost:8500"
  service_name: "Project-Service"
  service_id: "nextevent-go"
  health_check_interval: 10s
  deregister_critical_service_after: 30s

# Email Configuration
email:
  smtp:
    host: "smtp.qq.com"
    port: 587
    username: "brookyu@qq.com"
    password: "pejprdsamnjicaci"
    use_tls: true
    use_ssl: false
    from_address: "brookyu@qq.com"
    from_name: "样品索取"
    receiver: "brookyu@qq.com"
    timeout: 30s

# Media and File Configuration
media:
  base_url: "https://secure.zenteamserver.com"
  base_local_path: "/Users/brookyu/Codes/abp-vnext-pro-5.0.0.3/aspnet-core/services/host/ZenTeam.NextEvent.HttpApi.Host/wwwroot/"
  temp_dir: "temp"
  max_file_size: 104857600 # 100MB
  allowed_extensions: [".jpg", ".jpeg", ".png", ".gif", ".pdf", ".doc", ".docx", ".xls", ".xlsx"]
  image_quality: 85
  thumbnail_sizes:
    small: "150x150"
    medium: "300x300"
    large: "800x600"

# WeChat Server Configuration
wechat_server:
  base_url: "http://s2yms.zenteamserver.com"
  timeout: 30s
  retry_count: 3

# Live Streaming Configuration
live_streaming:
  player_url: "http://localhost:3000"
  cast_server_url: "http://cast.colorcon.wemakecrm.com"
  rtmp_server: "rtmp://localhost:1935"
  hls_server: "http://localhost:8080"

# Cache Configuration
cache:
  default_expiration: 3600s # 1 hour
  cleanup_interval: 600s    # 10 minutes
  max_items: 10000

# Rate Limiting
rate_limit:
  enabled: true
  requests_per_minute: 60
  burst: 10
  cleanup_interval: 60s

# Security Configuration
security:
  bcrypt_cost: 12
  max_login_attempts: 5
  lockout_duration: 900s # 15 minutes
  password_min_length: 8
  require_uppercase: true
  require_lowercase: true
  require_numbers: true
  require_symbols: false

# Monitoring and Health Checks
monitoring:
  enabled: true
  metrics_path: "/metrics"
  health_path: "/health"
  pprof_enabled: true
  pprof_path: "/debug/pprof"

# Feature Flags
features:
  analytics_enabled: true
  wechat_integration_enabled: true
  elasticsearch_enabled: false
  consul_enabled: false
  email_enabled: true
  file_upload_enabled: true
  live_streaming_enabled: true
